import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
        <footer className="border-t border-stone-200 px-6 py-6 text-center text-sm text-stone-400">
          <a href="https://digitalheroesco.com" target="_blank" rel="noopener noreferrer" className="hover:text-stone-600">
            Built for Digital Heroes Training Task
          </a>
        </footer>
      </body>
    </html>
  )
}
